#!/bin/bash
###################################################
# Script to create a new python project with pyenv
# It will automatically create a virualenv based
# on a configurable python version
# It is setup in such a way, that the virtualenv
# is automatically activate / deactivated when cd-ing
# in or out the root or child folders of the project
# #################################################

# Prompt the user for input
read -p "Choose python version (e.g., 3.11.2): " python_version

rm -rf .venv mise.toml mise.local.toml

mise use python@$python_version

virtualenv -p $(mise which python) .venv

mv mise.toml mise.local.toml
echo '[env]' >> mise.local.toml
echo '_.python.venv = ".venv"' >> mise.local.toml
