#!/bin/bash
if ! tmux has-session -t MONITORING 2> /dev/null; then
  tmux new-session -d -s MONITORING -n monitoring -x `tput cols` -y `tput lines`
  tmux split-window -t MONITORING:monitoring -h -p 40 -c ~/
  tmux send-keys -t MONITORING:monitoring.1 'htop' Enter
  tmux send-keys -t MONITORING:monitoring.2 'bmon' Enter
  tmux switch -t MONITORING
else
  tmux switch -t MONITORING
fi

